### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by r-lamarque** [cibr-jyu/meggie#23]
Hello,

I am quite new to both mne-python and python in general, so I wanted to try out Meggie which seems very practical. Unfortunately, I cannot install it. First, there seems to be an issue when creating the environment

> (base) C:\Users\Lamarque>conda create -n meggie-env -c conda-forge meggie
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

The second "solving environment" takes a lot of time, but from there, it seems to be installing just fine. However, when activating the environment and running "meggie", I get a fatal error:

> (base) C:\Users\Lamarque>conda activate meggie-env

> (meggie-env) C:\Users\Lamarque>meggie
Fatal error in launcher: Unable to create process using '"D:\bld\meggie_1671057991386\_h_env\python.exe"  "C:\Users\Lamarque\anaconda3\envs\meggie-env\Scripts\meggie.exe" ': The system cannot find the file specified.

Am I doing something wrong? Can someone help me with this?

Best regards,
Rémi Lamarque

**Comment by Teekuningas** [comment]
Hi!

The commands you use seem fine. You are using Windows right? Are you using Anaconda Prompt to run the commands? Is this a fresh install of Anaconda? If not, could you consider reinstalling Anaconda if that would help..?

Hope we'll get it to work!
Tk

**Comment by r-lamarque** [comment]
Hello,

Thank you for you answer. I am using Windows indeed. And I do use the Anaconda Prompt. I got that error on a brand new PC (Windows 11), and a brand new install of Anaconda. It is basically the first thing I tried to do on that PC. But I got a similar result on my old PC (Windows 10), and a colleague tried to install on his own PC with the same result.

So I think there may be something we are missing/doing wrong. Do we need to install something else first? We have a recent enough version of python and mne-python.

Best,
Rémi

**Comment by Teekuningas** [comment]
Ok, thanks for the information! I'll try to replicate and then fix the problem.

Best,
Erkka

**Comment by Teekuningas** [comment]
Ok, it seems conda build system on windows does not magically get the setuptools entry_points right and thus they need to be explicitly specified in the meta.yaml:

https://github.com/conda-forge/meggie-feedstock/commit/2b7d5eeb4fc8f3af36e2314b1800dec30f989088

Anyway, you should now be able to get the fixed version by entering the already existing environment and then installing again. So, in Anaconda Prompt:

```
> conda activate meggie-env
> conda install -c conda-forge meggie
> meggie
```

This should replace the broken version with a fixed one. It should not take as long as it takes with the from-scratch installation. Hope it works and thanks for letting us know! 

The long installation times are, I think, inevitable with the ambitious dependency resolution mechanisms of conda and the large search spaces. One might be able to guide it by specifying some of the versions, maybe like:

```
> conda create -n meggie-env -c conda-forge python=3.10 meggie=1.4.3 mne=1.3.0
```

Best regards,
-- Erkka

**Comment by r-lamarque** [comment]
Hello,

I was not able to fix the existing environment, but I removed everything and tried again with "conda create -n meggie-env -c conda-forge meggie", and now it works!

Also, the long installation is not really a problem. It's still manageable. I just mentioned it as it was not working and I thought it may be relevant to the issue.

Thank you very much for your help!

Best regards,
Rémi Lamarque
